---
alias: Bathroom Lights Occupancy
description: Turn on bathroom lights when door is open and presence detected (prevents triggering from hall)
id: 0502c715-74bd-461e-8fc7-189e8b6e4a0f

mode: restart
max_exceeded: silent

trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.bathroom_presence
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.bathroom_presence
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
  # Door opened - check if presence already detected
  - platform: state
    entity_id: binary_sensor.bathroom_door
    from: "off"
    to: "on"
conditions: []
action:
  - choose:
      # If someone is in and door is open
      - conditions:
          - condition: state
            entity_id: binary_sensor.bathroom_presence
            state: "on"
          - condition: state
            entity_id: binary_sensor.bathroom_door
            state: "on"
        sequence:
          - choose:
              # When dark, turn on ambient light
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.outdoor_is_dark
                    state: "on"
                sequence:
                  - alias: "Turn on ambient light"
                    service: light.turn_on
                    target:
                      entity_id: light.bathroom_ambient

              # When not dark, turn on main light
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.outdoor_is_dark
                    state: "off"
                sequence:
                  - alias: "Turn on main light"
                    service: light.turn_on
                    target:
                      entity_id: light.bathroom_main

      # If there's no one in
      - conditions:
          - condition: state
            entity_id: binary_sensor.bathroom_presence
            state: "off"
        sequence:
          - alias: "Turn off the light"
            service: light.turn_off
            target:
              entity_id:
                - light.bathroom_main
                - light.bathroom_ambient
                - light.bathroom_mirror
