---
binary_sensor:
  - name: stairway_presence
    device_class: occupancy
    state: >
      {{ is_state(
        "binary_sensor.first_floor_stairs_presence", "on"
      ) or is_state(
        "binary_sensor.ground_floor_stairs_presence", "on"
      ) }}
