- id: '1711110920292'
  alias: Fibaro S1 one click
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      value: KeyPressed
      property_key: '001'
  condition: []
  action:
  - type: toggle
    device_id: 6515f18582b879c34c729e9928d6db85
    entity_id: c5127906e5c2c8aae16d35623595c2e9
    domain: light
  mode: single
- id: '1711119915500'
  alias: double click
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 4
      value: KeyHeldDown
      property_key: '001'
  condition: []
  action:
  - device_id: 6515f18582b879c34c729e9928d6db85
    domain: light
    entity_id: c5127906e5c2c8aae16d35623595c2e9
    type: brightness_decrease
  mode: single
- id: '1717767424235'
  alias: TV ON - zaslony
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: b227c8aa094cde1a56f99d2ea73160a1
    entity_id: a94f8e3bd1616486a3169471d018f826
    domain: remote
  condition:
  - type: is_illuminance
    condition: device
    device_id: fba1c4bf1805f83d7da0953c6fbdc9f7
    entity_id: 1fc13964765c35baa40e27c114e433e5
    domain: sensor
    above: 400
  action:
  - device_id: 12d237d2ca69b214d29e113a23635832
    domain: cover
    entity_id: f4eb50ccbb96dbfd5bcbbc90636e3186
    type: close
  - type: turn_off
    device_id: 69a2fd46ea1ff43df14b26e00399e410
    entity_id: c864d60fa60266d4a31ff42fa573160a
    domain: switch
  mode: single
- id: '1717767553344'
  alias: TV off - zaslony out
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: b227c8aa094cde1a56f99d2ea73160a1
    entity_id: a94f8e3bd1616486a3169471d018f826
    domain: remote
  condition:
  - condition: sun
    before: sunset
  action:
  - device_id: 12d237d2ca69b214d29e113a23635832
    domain: cover
    entity_id: f4eb50ccbb96dbfd5bcbbc90636e3186
    type: open
  mode: single
- id: '1718039912293'
  alias: Kuchnia in
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: d783d02e28c54b1b7309b614637f1d2a
    entity_id: 20ac4d8d8df08b5d9f13ec02b1caa774
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
  - type: turn_on
    device_id: c5fccdc0362d76ef8a0d52fd31692f7f
    entity_id: c1a1a283e7ea21da5b77465fe7fc6866
    domain: switch
  mode: single
- id: '1718039998067'
  alias: Kitchen out
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: d783d02e28c54b1b7309b614637f1d2a
    entity_id: 20ac4d8d8df08b5d9f13ec02b1caa774
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_off
    device_id: c5fccdc0362d76ef8a0d52fd31692f7f
    entity_id: c1a1a283e7ea21da5b77465fe7fc6866
    domain: switch
  mode: single
- id: '1718043097859'
  alias: kitchen/island/presence/on
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: d783d02e28c54b1b7309b614637f1d2a
    entity_id: 6ea78842c779ba61299f670fef14d91d
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 7098e18634fa01bf4b47bc20d87f8676
    entity_id: 6e4a5b2c4d3caecdfdc3b6317b9560a9
    domain: switch
  mode: single
- id: '1718043209468'
  alias: kitchen/island/presence/out
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: d783d02e28c54b1b7309b614637f1d2a
    entity_id: 6ea78842c779ba61299f670fef14d91d
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - type: turn_off
    device_id: 7098e18634fa01bf4b47bc20d87f8676
    entity_id: 6e4a5b2c4d3caecdfdc3b6317b9560a9
    domain: switch
  mode: single
- id: '1718047265157'
  alias: Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30:00
  condition: []
  action:
  - device_id: 12d237d2ca69b214d29e113a23635832
    domain: cover
    entity_id: f4eb50ccbb96dbfd5bcbbc90636e3186
    type: close
  - device_id: f55dad517c431ad435b4e47c3b65f073
    domain: cover
    entity_id: 89d8c4bdbc762aa330d3933c61fe336c
    type: close
  - device_id: 6b3f12ef9f5b5abfaf40a3c98d15fcfb
    domain: cover
    entity_id: f9db6e1bb27a2a81b9d65b7066a869d9
    type: close
  mode: single
- id: '1718047346183'
  alias: Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - device_id: 12d237d2ca69b214d29e113a23635832
    domain: cover
    entity_id: f4eb50ccbb96dbfd5bcbbc90636e3186
    type: open
  - device_id: f55dad517c431ad435b4e47c3b65f073
    domain: cover
    entity_id: 89d8c4bdbc762aa330d3933c61fe336c
    type: open
  - device_id: 6b3f12ef9f5b5abfaf40a3c98d15fcfb
    domain: cover
    entity_id: f9db6e1bb27a2a81b9d65b7066a869d9
    type: close
  mode: single
- id: '1718047772845'
  alias: Saloon/TV/Pause
  description: ''
  trigger:
  - platform: device
    device_id: b227c8aa094cde1a56f99d2ea73160a1
    domain: media_player
    entity_id: da444016af1fd81c1906e71697805799
    type: paused
  condition: []
  action:
  - type: turn_on
    device_id: 69a2fd46ea1ff43df14b26e00399e410
    entity_id: 2c0b944d3730475d575bd1ec375ac251
    domain: switch
  mode: single
- id: '1718047836149'
  alias: Saloon/TV/Start
  description: ''
  trigger:
  - platform: device
    device_id: 872329f98a524bc1ddd4c493a4a7da49
    domain: media_player
    entity_id: d649edd7c1729bb3cee0e1d30920e82f
    type: playing
  condition: []
  action:
  - type: turn_off
    device_id: 69a2fd46ea1ff43df14b26e00399e410
    entity_id: 2c0b944d3730475d575bd1ec375ac251
    domain: switch
  mode: single
- id: '1718118070593'
  alias: livingroom/sofa/enter
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_fp2_0a27_presence_sensor_3
    from:
    to: 'on'
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: 69a2fd46ea1ff43df14b26e00399e410
    entity_id: c864d60fa60266d4a31ff42fa573160a
    domain: switch
  mode: single
- id: '1718118378262'
  alias: livingroom/sofa/out
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_fp2_0a27_presence_sensor_3
    from:
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - type: turn_off
    device_id: 69a2fd46ea1ff43df14b26e00399e410
    entity_id: c864d60fa60266d4a31ff42fa573160a
    domain: switch
  mode: single
- id: '1718119298608'
  alias: ground-floor/stairs/in
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_fp2_0a27_presence_sensor_2_2
    from:
    to: 'on'
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: c5ce3551490ae2c04a6a5d3411c2ef35
    entity_id: 7e4505b4c62eb830e171ab8e714d52cf
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - type: turn_off
    device_id: c5ce3551490ae2c04a6a5d3411c2ef35
    entity_id: 7e4505b4c62eb830e171ab8e714d52cf
    domain: switch
  mode: single
- id: '1718119432040'
  alias: ground-floor/stairs/out
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_fp2_0a27_presence_sensor_2_2
    from:
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - type: turn_off
    device_id: c5ce3551490ae2c04a6a5d3411c2ef35
    entity_id: 7e4505b4c62eb830e171ab8e714d52cf
    domain: switch
  mode: single
- id: '1718122099739'
  alias: Ground Floor / No one in
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_fp2_f1c5_presence_sensor_1_2
    from:
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.presence_sensor_fp2_0a27_presence_sensor_1_2
    state: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - condition: time
    after: '22:00:00'
  action:
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.ground_floor_lights_off
  mode: single
- id: '1718123676398'
  alias: First Floor / Stairs /In
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_sensor_fp2_e1a4_presence_sensor_3
    from:
    to: 'on'
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: c5ce3551490ae2c04a6a5d3411c2ef35
    entity_id: 7e4505b4c62eb830e171ab8e714d52cf
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - type: turn_off
    device_id: c5ce3551490ae2c04a6a5d3411c2ef35
    entity_id: 7e4505b4c62eb830e171ab8e714d52cf
    domain: switch
  mode: single
