---
alias: kitchen_turn_on_lights_when_occupied
description: Turn on the kitchen led lights when kitchen occupied
id: 2441c759-3b60-497b-99d0-4bd1d6f1ef28

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.kitchen_occupied
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: sensor.presence_sensor_fp2_ground_floor_light_level
    below: 10

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target:
      entity_id: light.kitchen_led

  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: binary_sensor.kitchen_occupied
      from: "on"
      to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: 10

  # If we're already during sleep time, stop the automation
  - if:
      - condition: state
        entity_id: input_boolean.cooking_mode
        state: "on"
    then:
      - stop: "Cooking mode is on. Let's not turn off the lights"

  - alias: "Turn off the light"
    service: light.turn_off
    target:
      entity_id: light.kitchen_led
