---
alias: Living room curtains
description: living_room_curtains
id: 27b3c9f1-c2c3-46c5-bd2a-2bd47abbfe20

mode: restart
max_exceeded: silent

trigger:
  - trigger: state
    entity_id: binary_sensor.dark_for_curtains
conditions: []
action:
  - choose:
      # Close covers when dark - check each cover independently
      - alias: "Dark - close any open covers"
        conditions:
          - condition: state
            entity_id: binary_sensor.dark_for_curtains
            state: "on"
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: cover.living_room_main
                    state: "closed"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: cover.living_room_left
                    state: "closed"
        sequence:
          - alias: "Close all living room covers"
            service: cover.close_cover
            target:
              area_id: living_room

      # Open covers when not dark - check each cover independently
      - alias: "Not dark - open any closed covers"
        conditions:
          - condition: state
            entity_id: binary_sensor.dark_for_curtains
            state: "off"
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: cover.living_room_main
                    state: "open"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: cover.living_room_left
                    state: "open"
        sequence:
          - alias: "Open all living room covers"
            service: cover.open_cover
            target:
              area_id: living_room
