---
alias: Living room humidifier humidity control
description: >-
  Toggle humidification_active flag based on current humidity. Evening prep
  (17:00–bed_time) targets 45% (off@45, on@40). Otherwise targets 40%
  (off@40, on@38). Humidifier stays physically on — fan speed automation
  handles idle standby when flag is off.
id: d4f6c0a3-8e5b-4h8d-1c3g-7f0e4d2b5c96

mode: restart
max_exceeded: silent

trigger:
  - trigger: numeric_state
    entity_id: humidifier.living_room
    attribute: current_humidity
    below: 38
    id: "below_38"
  - trigger: numeric_state
    entity_id: humidifier.living_room
    attribute: current_humidity
    below: 40
    id: "below_40"
  - trigger: numeric_state
    entity_id: humidifier.living_room
    attribute: current_humidity
    above: 40
    id: "above_40"
  - trigger: numeric_state
    entity_id: humidifier.living_room
    attribute: current_humidity
    above: 45
    id: "above_45"
  - trigger: state
    entity_id: binary_sensor.evening_prep
    id: "period_change"
  - trigger: homeassistant
    event: start
    id: "startup"
  - trigger: event
    event_type: automation_reloaded
    id: "startup"

condition:
  - condition: state
    entity_id: humidifier.living_room
    state: "on"

action:
  - variables:
      humidity: >
        {{ state_attr('humidifier.living_room', 'current_humidity') | float(0) }}
      off_target: >
        {{ 45 if is_state('binary_sensor.evening_prep', 'on') else 40 }}
      on_target: >
        {{ 40 if is_state('binary_sensor.evening_prep', 'on') else 38 }}
  - choose:
      - alias: "Deactivate - humidity reached target"
        conditions:
          - condition: template
            value_template: "{{ humidity >= off_target }}"
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.living_room_humidification_active

      - alias: "Activate - humidity dropped below threshold"
        conditions:
          - condition: template
            value_template: "{{ humidity < on_target }}"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.living_room_humidification_active
