---
alias: living_room_open_cover_windows_when_sunrise
description: Open Living room covers on sunrise
id: d90570af-b4e4-4213-8bc4-c4b050838398

mode: single

trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:00"

condition: []

action:
  - service: cover.open_cover
    target:
      area_id: living_room
