---
alias: living_room_close_cover_windows_when_sunset
description: Close Living room covers on sunset
id: 27b3c9f1-c2c3-46c5-bd2a-2bd47abbfe20

mode: single

trigger:
  - platform: sun
    event: sunset
    offset: "00:20:00"

condition: []

action:
  - service: cover.close_cover
    target:
      area_id: living_room
