---
alias: Living room humidifier fan speed
description: >-
  Adjust humidifier fan speed based on presence and humidification state.
  When humidification inactive: idle at 40%. When active: 40% occupied,
  80% vacant.
id: b2f4a8e1-7c3d-4f6b-9a1e-5d8c2b0f3a74

mode: restart
max_exceeded: silent

trigger:
  - trigger: state
    entity_id: binary_sensor.living_room_presence
    from: "off"
    to: "on"
    id: "occupied"
  - trigger: state
    entity_id: binary_sensor.living_room_presence
    from: "on"
    to: "off"
    for:
      seconds: 30
    id: "vacant"
  - trigger: state
    entity_id: humidifier.living_room
    from: "off"
    to: "on"
    id: "turned_on"
  - trigger: homeassistant
    event: start
    id: "startup"
  - trigger: event
    event_type: automation_reloaded
    id: "startup"
  - trigger: state
    entity_id: input_boolean.living_room_humidification_active
    id: "humidification_changed"

condition:
  - condition: state
    entity_id: humidifier.living_room
    state: "on"

action:
  - choose:
      - alias: "Idle standby - humidification not needed (40%)"
        conditions:
          - condition: state
            entity_id: input_boolean.living_room_humidification_active
            state: "off"
        sequence:
          - alias: "Set humidifier to normal mode"
            action: humidifier.set_mode
            target:
              entity_id: humidifier.living_room
            data:
              mode: normal
          - alias: "Set fan to idle (40%)"
            action: fan.set_percentage
            target:
              entity_id: fan.living_room_humidifier
            data:
              percentage: 40

      - alias: "Active + occupied - quiet mode (normal 40%)"
        conditions:
          - condition: state
            entity_id: input_boolean.living_room_humidification_active
            state: "on"
          - condition: state
            entity_id: binary_sensor.living_room_presence
            state: "on"
        sequence:
          - alias: "Set humidifier to normal mode"
            action: humidifier.set_mode
            target:
              entity_id: humidifier.living_room
            data:
              mode: normal
          - alias: "Set fan to 40%"
            action: fan.set_percentage
            target:
              entity_id: fan.living_room_humidifier
            data:
              percentage: 40

      - alias: "Active + vacant - boost mode (normal 80%)"
        conditions:
          - condition: state
            entity_id: input_boolean.living_room_humidification_active
            state: "on"
          - condition: state
            entity_id: binary_sensor.living_room_presence
            state: "off"
        sequence:
          - alias: "Set humidifier to normal mode"
            action: humidifier.set_mode
            target:
              entity_id: humidifier.living_room
            data:
              mode: normal
          - alias: "Set fan to 80%"
            action: fan.set_percentage
            target:
              entity_id: fan.living_room_humidifier
            data:
              percentage: 80
