alias: Living Room TV
description: Living Room TV
unique_id: 9e959848-5de4-4e82-8874-5250fbc72929
triggers:
  - event: start
    trigger: homeassistant
  - event_type: automation_reloaded
    trigger: event
  - entity_id: media_player.living_room_tv
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: media_player.living_room_tv
            state: playing
          - condition: state
            entity_id: binary_sensor.living_room_is_dark
            state: "on"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.living_room_tv_leds_with_power
              rgb_color:
                - 255
                - 193
                - 132
              brightness_pct: 20

      - conditions:
          - condition: state
            entity_id: media_player.living_room_tv
            state: "off"
        sequence:
          - entity_id: light.living_room_tv_leds_with_power
            action: light.turn_off

      - conditions:
          - condition: state
            entity_id: binary_sensor.living_room_is_dark
            state: "on"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.living_room_tv_leds_with_power
              rgb_color:
                - 255
                - 193
                - 132
              brightness_pct: 80
mode: queued
max_exceeded: silent
