---
binary_sensor:
  - name: stairway_occupied
    device_class: occupancy
    state: >
      {{ is_state(
        "binary_sensor.presence_sensor_fp2_1st_floor_corridor_stairs", "on"
      ) or is_state(
        "binary_sensor.ground_floor_stairs_presence", "on"
      ) }}
