---
template: !include_dir_list templates

timer:
  garden_park_gate_opening:
    name: Garden Park Gate Opening
    duration: "00:00:15"
  garden_park_gate_open:
    name: Garden Park Gate Open
    duration: "00:00:20"

cover:
  - platform: group
    name: All Gates
    unique_id: all_gates_group
    entities:
      - cover.garden_park_gate
      - cover.garage_door

rest_command:
  gate_open_call:
    url: !secret twilio_calls_url
    method: POST
    headers:
      Authorization: !secret twilio_auth_header
    payload: !secret twilio_gate_call_payload
    content_type: "application/x-www-form-urlencoded"
    verify_ssl: true

script:
  gate_open:
    alias: Open Gate
    description: Calls the gate GSM module via Twilio to open the gate
    icon: mdi:gate
    mode: single
    sequence:
      - action: rest_command.gate_open_call
