---
alias: Presence - ground floor absent for 1 min
description: Presence in the ground floors with 1 min threshold on no presence
id: 173458d4-d369-40ba-b239-7299293d1e31

mode: restart
max_exceeded: silent

trigger:
  - event: start
    trigger: homeassistant
  - event_type: automation_reloaded
    trigger: event
  - platform: state
    entity_id:
      - binary_sensor.ground_floor_presence
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.ground_floor_presence
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 1
      seconds: 0

action:
  - choose:
      # If someone is in ground floor
      - conditions:
          - condition: state
            entity_id: binary_sensor.ground_floor_presence
            state: "on"
        sequence:
          # Standing lamp: ON when dark OR christmas mode
          - if:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.living_room_is_dark
                    state: "on"
                  - condition: state
                    entity_id: input_boolean.christmas_mode
                    state: "on"
            then:
              - alias: "Turn on standing lamp"
                service: light.turn_on
                target:
                  entity_id: light.living_room_light_standing_lamp
          # Kitchen LEDs: ON only when Christmas mode AND dark
          - if:
              - condition: state
                entity_id: input_boolean.christmas_mode
                state: "on"
              - condition: state
                entity_id: binary_sensor.living_room_is_dark
                state: "on"
            then:
              - alias: "Turn on kitchen LEDs (Christmas mode)"
                service: light.turn_on
                target:
                  entity_id: light.kitchen_led

      # If there's no one in ground floor
      - conditions:
          - condition: state
            entity_id: binary_sensor.ground_floor_presence
            state: "off"
        sequence:
          - alias: "Turn off all ground floor lights"
            service: light.turn_off
            target:
              floor_id: ground_floor
