---
alias: presence_ground_floor_with_5_min_threshold
description: Presence in the ground floors with 5 min threshold on no presence
id: 173458d4-d369-40ba-b239-7299293d1e31

mode: restart
max_exceeded: silent

trigger:
  - event: start
    trigger: homeassistant
  - event_type: automation_reloaded
    trigger: event
  - platform: state
    entity_id:
      - binary_sensor.ground_floor_occupied
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.ground_floor_occupied
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 5
      seconds: 0

action:
  - choose:
      # If someone is in ground floor
      - conditions:
          - condition: and
            conditions:
                - condition: state
                  entity_id: binary_sensor.ground_floor_occupied
                  state: "on"
                - condition: state
                  entity_id: binary_sensor.living_room_is_dark
                  state: "on"
        sequence:
          - alias: "Turn on the light"
            service: light.turn_on
            target:
              entity_id: light.living_room_light_standing_lamp

      # If there's no one in ground floor
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.ground_floor_occupied
                state: "off"
        sequence:
          - alias: "Turn off the light"
            service: light.turn_off
            target:
              entity_id: light.living_room_light_standing_lamp
