---
alias: bedroom_lights_on_when_occupied
description: Turn on the bedroom lights when is occupied
id: e15fdeed-93c7-40fe-83b5-727e4639b86d

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_sensor_bedroom
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: sensor.presence_sensor_bedroom_light_level
    below: 10

    # don't trigger the automation during the sleep time
    # otherwise if the presence sensor stops recognising occupancy and then start again,
    # then the lights will turn on during the night :|
  - condition: time
    after: sensor.wakeup_time
    before: sensor.bed_time

  - condition: state
    entity_id: light.bedroom
    state: "off"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target:
      entity_id: light.bedroom_reflectors

  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: binary_sensor.presence_sensor_bedroom
      from: "on"
      to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: 15

  - alias: "Turn off the light"
    service: light.turn_off
    target:
      entity_id: light.bedroom_reflectors
