---
alias: bedroom_cover_windows_when_sunset_on_just_before_sunrise
description: Cover the bedroom windows on sunset or just before sunrise
id: 95466e53-ec2b-4c08-ad2b-c7edba4158ff

mode: single

trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"

  - platform: sun
    event: sunrise
    offset: "-01:00:00"

condition: []

action:
  - service: cover.close_cover
    target:
      area_id: bedroom

---
alias: bedroom_uncover_windows_when_sleeping_time_off
description: Uncover the bedroom windows when sleeping time is off
id: 3edc8a96-1be1-4396-88bc-da64ab5d7436

mode: single

trigger:
  - platform: state
    entity_id:
      - binary_sensor.sleeping_time
    from: "on"
    to: "off"

condition: []

action:
  - service: cover.open_cover
    target:
      area_id: bedroom
