---
binary_sensor:
  - name: bedroom_is_dark
    state: >
      {% if states('sensor.bedroom_illuminance') | float < 10
        or state_attr('sun.sun', 'elevation') | float < -2.0
      %}
        on
      {% else %}
        off
      {% endif %}
