---
binary_sensor:
  - name: bedroom_is_dark
    state: >
      {% if states('sensor.bedroom_illuminance') | float < 5
        or is_state("binary_sensor.garden_is_dark", "on")
      %}
        on
      {% else %}
        off
      {% endif %}
