---
binary_sensor:
  - name: ensuite_bathroom_is_dark
    state: >
      {% if states('sensor.ensuite_bathroom_illuminance') | float < 10
        or is_state("binary_sensor.garden_is_dark", "on")
      %}
        on
      {% else %}
        off
      {% endif %}
