---
binary_sensor:
  - name: ground_floor_occupied
    device_class: occupancy
    state: >
      {{ is_state(
        "binary_sensor.presence_sensor_fp2_ground_floor", "on"
      ) or is_state(
        "binary_sensor.presence_sensor_fp2_livingroom_stairs", "on"
      ) }}
