---
alias: kitchen_turn_on_lights_when_occupied
description: Turn on the kitchen led lights when kitchen occupied
id: 2441c759-3b60-497b-99d0-4bd1d6f1ef28

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.kitchen_occupied
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: sensor.presence_sensor_fp2_livingroom_light_level
    attribute: "0"
    below: 10000

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target:
      entity_id: light.kitchen_led

  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: binary_sensor.kitchen_occupied
      from: "on"
      to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: 10

  - alias: "Turn off the light"
    service: light.turn_off
    target:
      entity_id: light.kitchen_led
