---
alias: Living room humidifier fan speed
description: >-
  Set humidifier fan speed from the computed target speed sensor. The
  proportional speed is determined by
  sensor.living_room_humidifier_target_speed based on humidity gap, presence,
  and time period (evening_prep, office_hours).
id: b2f4a8e1-7c3d-4f6b-9a1e-5d8c2b0f3a74

mode: restart
max_exceeded: silent

trigger:
  - trigger: state
    entity_id: sensor.living_room_humidifier_target_speed
    not_to: "unavailable"
    id: "speed_changed"
  - trigger: state
    entity_id: humidifier.living_room
    from: "off"
    to: "on"
    id: "turned_on"
  - trigger: homeassistant
    event: start
    id: "startup"
  - trigger: event
    event_type: automation_reloaded
    id: "startup"

condition:
  - condition: state
    entity_id: humidifier.living_room
    state: "on"

action:
  - alias: "Set humidifier to normal mode"
    action: humidifier.set_mode
    target:
      entity_id: humidifier.living_room
    data:
      mode: normal

  - alias: "Set fan to computed target speed"
    action: fan.set_percentage
    target:
      entity_id: fan.living_room_humidifier
    data:
      percentage: >
        {{ states('sensor.living_room_humidifier_target_speed') | int(20) }}
