---
binary_sensor:
  - name: ensuite_bathroom_is_dark
    device_class: light
    delay_on: "00:00:05"
    delay_off: "00:00:30"
    state: >
      {{ states('sensor.ensuite_bathroom_illuminance') | float == 0 }}
    attributes:
      illuminance: "{{ states('sensor.ensuite_bathroom_illuminance') }}"
