---
alias: Garden lights from terrace doors and presence
description: >
  Terrace door opens or terrace presence detected after dark - turn on
  the garden lights group. Turn off all garden lights once terrace
  presence has been clear for 3 minutes.
id: f4bbc912-1ce9-41eb-93a9-273c9d764d9a

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.terrace_left_door
      - binary_sensor.terrace_main_door
    from: "off"
    to: "on"
    id: lights_on
  - platform: state
    entity_id: binary_sensor.terrace_presence
    from: "off"
    to: "on"
    id: lights_on
  - platform: state
    entity_id: binary_sensor.terrace_presence
    from: "on"
    to: "off"
    for: "00:03:00"
    id: lights_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: lights_on
          - condition: state
            entity_id: binary_sensor.outdoor_is_dark
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.garden_lights

      - conditions:
          - condition: trigger
            id: lights_off
        sequence:
          - service: light.turn_off
            target:
              area_id: garden
