---
alias: bathroom_presence
description: Turn on the bathroom lights when is occupied
id: 0502c715-74bd-461e-8fc7-189e8b6e4a0f

mode: restart
max_exceeded: silent

trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.bathroom_presence
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.bathroom_presence
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
conditions: []
action:
  - choose:
      # If someone is in
      - conditions:
          - condition: state
            entity_id: binary_sensor.bathroom_presence
            state: "on"
        sequence:
          - if:
              - condition: time
                after: "22:00:00"
            then:
              - service: light.turn_on
                target:
                  entity_id: light.bathroom_ambient
            else:
              - service: light.turn_on
                target:
                  entity_id: light.bathroom_main

      # If there's no one in
      - conditions:
          - condition: state
            entity_id: binary_sensor.bathroom_presence
            state: "off"
        sequence:
          - alias: "Turn off the light"
            service: light.turn_off
            target:
              entity_id:
                - light.bathroom_main
                - light.bathroom_ambient
