---
alias: Bedroom and ensuite vacancy timeout
description: Turn off all bedroom and ensuite lights after 10 minutes of no presence
id: a8f3c9d2-7e41-4b2a-9c1e-5d8f2b4e6a3c

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.bedroom_presence
      - binary_sensor.ensuite_bathroom_presence
    to: "off"
    for:
      minutes: 10

conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.bedroom_presence
        state: "off"
      - condition: state
        entity_id: binary_sensor.ensuite_bathroom_presence
        state: "off"

action:
  - alias: "Turn off all bedroom and ensuite lights"
    action: light.turn_off
    target:
      entity_id:
        - light.bedroom
        - light.ensuite_bathroom
