---
alias: Bedroom humidifier fan speed
description: >-
  Set humidifier fan speed from the computed target speed sensor. Night mode
  turns off the display; daytime restores it. The proportional speed is
  determined by sensor.bedroom_humidifier_target_speed based on humidity gap,
  presence, and time period.
id: c3e5b9f2-8d4a-4g7c-0b2f-6e9d3c1a4b85

mode: restart
max_exceeded: silent

trigger:
  - trigger: state
    entity_id: sensor.bedroom_humidifier_target_speed
    not_to: "unavailable"
    id: "speed_changed"
  - trigger: state
    entity_id: binary_sensor.bed_time
    from: "off"
    to: "on"
    id: "night"
  - trigger: state
    entity_id: binary_sensor.bed_time
    from: "on"
    to: "off"
    id: "morning"
  - trigger: state
    entity_id: humidifier.bedroom
    from: "off"
    to: "on"
    id: "turned_on"
  - trigger: homeassistant
    event: start
    id: "startup"
  - trigger: event
    event_type: automation_reloaded
    id: "startup"

condition:
  - condition: state
    entity_id: humidifier.bedroom
    state: "on"

action:
  - alias: "Manage display: off at night, on during day"
    choose:
      - alias: "Night - turn off display"
        conditions:
          - condition: state
            entity_id: binary_sensor.bed_time
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.bedroom_humidifier_display
    default:
      - action: light.turn_on
        target:
          entity_id: light.bedroom_humidifier_display

  - alias: "Set humidifier to normal mode"
    action: humidifier.set_mode
    target:
      entity_id: humidifier.bedroom
    data:
      mode: normal

  - alias: "Set fan to computed target speed"
    action: fan.set_percentage
    target:
      entity_id: fan.bedroom_humidifier
    data:
      percentage: >
        {{ states('sensor.bedroom_humidifier_target_speed') | int(20) }}
