---
alias: bathroom_lights_on_when_occupied
description: Turn on the bathroom lights when is occupied
id: 0502c715-74bd-461e-8fc7-189e8b6e4a0f

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_sensor_bahtroom
    from: "off"
    to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target:
      entity_id: light.main_bathroom_main

  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: binary_sensor.presence_sensor_bahtroom
      from: "on"
      to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: 15

  - alias: "Turn off the light"
    service: light.turn_off
    target:
      entity_id: light.main_bathroom_main
