---
alias: laundry_room_lights_on_when_occupied
description: >-
  Turn on laundry room lights when movement detected or door opens,
  with safety timeout
id: 618bc813-203f-42cc-8a55-21e89c0ca4b1

mode: restart
max_exceeded: silent

trigger:
  # Movement detected
  - platform: state
    entity_id: binary_sensor.laundry_room_sensor_occupancy
    from: "off"
    to: "on"
    id: "occupancy_detected"

  # Door opened
  - platform: state
    entity_id: binary_sensor.laundry_doors
    from: "off"
    to: "on"
    id: "door_opened"

  # Door closed
  - platform: state
    entity_id: binary_sensor.laundry_doors
    from: "on"
    to: "off"
    id: "door_closed"

  # Safety timeout - 5 minutes after occupancy ends
  - platform: state
    entity_id: binary_sensor.laundry_room_sensor_occupancy
    from: "on"
    to: "off"
    for: "00:05:00"
    id: "safety_timeout"

action:
  - choose:
      # Occupancy detected or door opened - turn on light
      - conditions:
          - condition: trigger
            id:
              - "occupancy_detected"
              - "door_opened"
          - condition: state
            entity_id: light.laundry
            state: "off"
        sequence:
          - alias: "Turn on the light"
            action: light.turn_on
            target:
              entity_id: light.laundry

      # Door closed - turn off lights
      - conditions:
          - condition: trigger
            id: "door_closed"
        sequence:
          - alias: "Turn off the light (door closed)"
            action: light.turn_off
            target:
              entity_id: light.laundry

      # Safety timeout - turn off lights after 5 min of no occupancy
      - conditions:
          - condition: trigger
            id: "safety_timeout"
        sequence:
          - alias: "Turn off the light (safety timeout)"
            action: light.turn_off
            target:
              entity_id: light.laundry
