---
binary_sensor:
  - name: ground_floor_presence
    device_class: occupancy
    state: >
      {{ is_state(
        "binary_sensor.common_area_presence", "on"
      ) or is_state(
        "binary_sensor.living_room_presence", "on"
      )
      }}
