---
binary_sensor:
  - name: ground_floor_light_status
    state: >
      {% set ignored_lights=[
        "light.living_room_tv_up",
        "light.living_room_tv_down",
        "light.living_room_leds"
      ] %}
      {% if floor_areas('ground_floor') | map('area_entities') | sum(start=[]) | select('match', 'light') 
        | reject('in', ignored_lights) | select('is_state', 'on') | list | length > 0 %}
        on
      {% else %}
        off
      {% endif %}
