---
alias: boiler_room_lights_on_when_occupied
description: Turn on boiler room lights when presence detected, off after 10s
id: 7a2e4c89-5f31-4d8a-b6c2-9e8d1f3a5b7c

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: binary_sensor.boiler_room_occupancy
    from: "off"
    to: "on"
    id: "on"

  - platform: state
    entity_id: binary_sensor.boiler_room_occupancy
    from: "on"
    to: "off"
    for: "00:00:10"
    id: "off"

action:
  - action: "light.turn_{{ trigger.id }}"
    target:
      entity_id: light.boiler_room
