---
alias: Living room curtains
description: living_room_curtains
id: 8c4dfa1a-b0ab-4b7e-bd88-5bdb8e5c17a8

mode: restart
max_exceeded: silent

trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - trigger: state
    entity_id: sun.sun
    from: below_horizon
    to: above_horizon
  - trigger: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
    for:
      hours: 0
      minutes: 30
      seconds: 0
conditions: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: "above_horizon"
        sequence:
          - action: light.turn_off
            target:
              area_id: porch

      - conditions:
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
        sequence:
          - action: light.turn_on
            target:
              area_id: porch
