---
alias: Porch doorbell notify tablet
description: Wake tablet and show doorbell camera popup when doorbell rings
id: porch-doorbell-notify-tablet

mode: restart

trigger:
  - platform: state
    entity_id: event.doorbell
    not_from:
      - unavailable
      - unknown
    not_to:
      - unavailable
      - unknown

action:
  # Turn on tablet screen
  - action: switch.turn_on
    target:
      entity_id: switch.kitchen_dashboard_screen

  # Show camera popup (instant, no page reload)
  - action: browser_mod.popup
    target:
      device_id: 160f29e2269bc5977ba906031935bb70
    data:
      title: Doorbell
      timeout: 15000
      content:
        type: picture-entity
        entity: camera.porch
        camera_view: live
        show_state: false
        show_name: false
