---
alias: porch_turn_on_lights_after_sunset
description: Turn on porch lights after sunset
id: 4d64810d-da45-4351-a5dd-52b3991be354

mode: single

trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"

action:
  - action: light.turn_on
    target:
      area_id: porch
