---
alias: Bedroom Sona Dial Switch
description: Sona's dial - controls bedroom light brightness via rotation, toggle/off via button
id: e60904ec-3ce6-1886-e094-0c028659abbf

triggers:
  - platform: mqtt
    topic: "zigbee2mqtt/sona_bedroom_switch"

variables:
  action: "{{ trigger.payload_json.action }}"
  delta: "{{ trigger.payload_json.action_brightness_delta | default(20) | int }}"
  step_pct: "{{ ((delta / 255) * 100) | int | max(1) }}"

actions:
  - choose:
      # Brightness up
      - conditions:
          - condition: template
            value_template: "{{ action == 'brightness_move_up' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: "{{ step_pct }}"
              transition: 0.3

      # Brightness down
      - conditions:
          - condition: template
            value_template: "{{ action == 'brightness_move_down' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: "{{ -step_pct }}"
              transition: 0.3

      # Button short press - toggle light
      - conditions:
          - condition: template
            value_template: "{{ action == 'button_short_release' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_sona_with_power

      # Button long press - turn off light
      - conditions:
          - condition: template
            value_template: "{{ action == 'button_long_release' }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.bedroom_sona_with_power

mode: restart
