---
alias: Bedroom humidifier night mode
description: >-
  At 22:00, set humidifier to quiet night mode (screen off, manual mode,
  lowest fan speed). At 08:00, restore normal operation (screen on, auto mode).
id: a7e1c3f4-8d2b-4e9a-b6f1-3c5d7a9e2b10

mode: single

trigger:
  - trigger: time
    at: "22:00:00"
    id: "night"
  - trigger: time
    at: "08:00:00"
    id: "morning"

conditions: []

action:
  - choose:
      - alias: "Night - quiet mode"
        conditions:
          - condition: trigger
            id: "night"
          - condition: state
            entity_id: humidifier.bedroom
            state: "on"
        sequence:
          - alias: "Turn off humidifier display"
            action: light.turn_off
            target:
              entity_id: light.bedroom_humidifier_display
          - alias: "Set humidifier to manual mode (required before setting fan speed)"
            action: humidifier.set_mode
            target:
              entity_id: humidifier.bedroom
            data:
              mode: normal
          - alias: "Set fan to lowest speed"
            action: fan.set_percentage
            target:
              entity_id: fan.bedroom_humidifier
            data:
              percentage: 20

      - alias: "Morning - restore normal operation"
        conditions:
          - condition: trigger
            id: "morning"
          - condition: state
            entity_id: humidifier.bedroom
            state: "on"
        sequence:
          - alias: "Turn on humidifier display"
            action: light.turn_on
            target:
              entity_id: light.bedroom_humidifier_display
          - alias: "Set humidifier to auto mode"
            action: humidifier.set_mode
            target:
              entity_id: humidifier.bedroom
            data:
              mode: auto
