---
alias: Bedroom Wardrobe Light Switch
description: Bedroom Scene Switch - wardrobe light toggle
id: 38fcd1d1-292c-4e13-8d52-af8b78a21df2

triggers:
  - domain: mqtt
    device_id: 42a3d9a108ccf15bca1014a5148c16c6
    type: action
    subtype: single
    trigger: device

actions:
  - action: light.toggle
    target:
      entity_id: light.bedroom_wardrobe

mode: single
