---
alias: Bedroom Wardrobe Light Switch
description: Bedroom Scene Switch - wardrobe light toggle
id: 38fcd1d1-292c-4e13-8d52-af8b78a21df2

triggers:
  - trigger: state
    entity_id:
      - sensor.bedroom_scene_switch

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_wardrobe

mode: single
