---
alias: Bedroom presence
description: Turn on bedroom lights when someone is in
id: 13b5c7e1-409e-485e-b52b-b4f07adbe059

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.bedroom_entrance_presence
      - binary_sensor.bedroom_presence
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.bedroom_entrance_presence
      - binary_sensor.bedroom_presence
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 5

  - platform: state
    entity_id:
      - binary_sensor.presence_sensor_bedroom_jakub_side
      - binary_sensor.presence_sensor_bedroom_sona_side
    to: "on"
conditions: []
action:
  - choose:
      # If it's dark and someone is present in any bedroom area,
      # but it's not sleeping time and other lights or tv are not on
      - conditions:
          - condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.bedroom_entrance_presence
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.bedroom_walking_area_presence
                    state: "on"
              - condition: state
                entity_id: binary_sensor.bedroom_is_dark
                state: "on"
              - condition: state
                entity_id: binary_sensor.sleeping_time
                state: "off"
              - condition: state
                entity_id: light.bedroom
                state: "off"
              - condition: state
                entity_id: media_player.bedroom_tv
                state: "off"

        sequence:
          - service: light.turn_on
            target:
              entity_id: light.bedroom_reflectors

      # If it's dark sleeping time with entrance presence, TV off and other lights off
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.bedroom_entrance_presence
                state: "on"
              - condition: state
                entity_id: binary_sensor.bedroom_is_dark
                state: "on"
              - condition: state
                entity_id: binary_sensor.sleeping_time
                state: "on"
              - condition: state
                entity_id: media_player.bedroom_tv
                state: "off"
              - condition: state
                entity_id: light.bedroom
                state: "off"

        sequence:
          - service: light.turn_on
            target:
              entity_id: light.bed_stripe
            data:
              brightness_pct: 30
              rgb_color: [249, 255, 194]

      # If bed presence sensors detect someone during sleeping time with TV and lights off
      - conditions:
          - condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.presence_sensor_bedroom_jakub_side
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.presence_sensor_bedroom_sona_side
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.bedroom_walking_area_presence
                    state: "on"
              - condition: state
                entity_id: binary_sensor.bedroom_is_dark
                state: "on"
              - condition: state
                entity_id: binary_sensor.sleeping_time
                state: "on"
              - condition: state
                entity_id: media_player.bedroom_tv
                state: "off"
              - condition: state
                entity_id: light.bedroom
                state: "off"

        sequence:
          - alias: "Turn on bed stripe at minimum brightness"
            service: light.turn_on
            target:
              entity_id: light.bed_stripe
            data:
              brightness_pct: 2
              rgb_color: [249, 255, 194]
          - alias: "Turn on bed stripe at minimum brightness"
            service: light.turn_on
            target:
              entity_id: light.bed_stripe
            data:
              brightness_pct: 1
              rgb_color: [ 249, 255, 194 ]
          - alias: "Wait for 5 seconds"
            delay:
              seconds: 5
          - alias: "Turn off bed stripe"
            service: light.turn_off
            target:
              entity_id: light.bed_stripe

      # If there's no one in bedroom or ensuite bathroom
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.bedroom_presence
                state: "off"
              - condition: state
                entity_id: binary_sensor.ensuite_bathroom_presence
                state: "off"
        sequence:
          - alias: "Turn off the light"
            service: light.turn_off
            target:
              entity_id: light.bedroom
