---
alias: bedroom_cover_windows_when_sunset_on_just_before_sunrise
description: Cover the bedroom windows on sunset or just before sunrise
id: 95466e53-ec2b-4c08-ad2b-c7edba4158ff

mode: single

trigger:
  - platform: sun
    event: sunrise
    offset: "-01:00:00"

  - trigger: state
    entity_id: binary_sensor.dark_for_curtains
    to: "on"

condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: cover.bedroom
        state: "closed"

action:
  - service: cover.close_cover
    target:
      area_id: bedroom
