---
alias: Bedroom Sona Dial Switch
description: Sona's dial - controls bedroom light brightness via rotation, toggle/off via button
id: e60904ec-3ce6-1886-e094-0c028659abbf

triggers:
  # Dial rotation
  - domain: mqtt
    device_id: e60904ec3ce61886e0940c028659abbf
    type: action
    subtype: dial_rotate_right_fast
    trigger: device
  - domain: mqtt
    device_id: e60904ec3ce61886e0940c028659abbf
    type: action
    subtype: dial_rotate_right_slow
    trigger: device
  - domain: mqtt
    device_id: e60904ec3ce61886e0940c028659abbf
    type: action
    subtype: dial_rotate_left_fast
    trigger: device
  - domain: mqtt
    device_id: e60904ec3ce61886e0940c028659abbf
    type: action
    subtype: dial_rotate_left_slow
    trigger: device
  # Button press
  - domain: mqtt
    device_id: e60904ec3ce61886e0940c028659abbf
    type: action
    subtype: button_short_release
    trigger: device
  - domain: mqtt
    device_id: e60904ec3ce61886e0940c028659abbf
    type: action
    subtype: button_long_release
    trigger: device

actions:
  - choose:
      # Dial rotate right fast - increase brightness 25%
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'dial_rotate_right_fast' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: 25

      # Dial rotate right slow - increase brightness 10%
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'dial_rotate_right_slow' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: 10

      # Dial rotate left fast - decrease brightness 25%
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'dial_rotate_left_fast' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: -25

      # Dial rotate left slow - decrease brightness 10%
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'dial_rotate_left_slow' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: -10

      # Button short press - toggle light
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'button_short_release' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_sona_with_power

      # Button long press - turn off light
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'button_long_release' }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.bedroom_sona_with_power

mode: single
