---
alias: Bedroom Sona Dial Switch
description: Sona's dial - controls bedroom light brightness via rotation, toggle/off via button
id: e60904ec-3ce6-1886-e094-0c028659abbf

triggers:
  - platform: mqtt
    topic: "zigbee2mqtt/sona_bedroom_switch"

variables:
  action: "{{ trigger.payload }}"
  step_pct: "{{ 50 if 'fast' in action else 10 }}"

actions:
  - choose:
      # Dial rotate right
      - conditions:
          - condition: template
            value_template: "{{ action in ['dial_rotate_right_fast', 'dial_rotate_right_slow'] }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: "{{ step_pct }}"
              transition: 0.3

      # Dial rotate left
      - conditions:
          - condition: template
            value_template: "{{ action in ['dial_rotate_left_fast', 'dial_rotate_left_slow'] }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.bedroom_sona_with_power
            data:
              brightness_step_pct: "{{ -step_pct }}"
              transition: 0.3

      # Button short press - toggle
      - conditions:
          - condition: template
            value_template: "{{ action == 'button_short_release' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_sona_with_power

      # Button long press - off
      - conditions:
          - condition: template
            value_template: "{{ action == 'button_long_release' }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.bedroom_sona_with_power

mode: restart
