---
# Consolidated from:
# - bedroom_switch_off_big_lights_when_bed_lights_on.yaml
# - bedroom_switch_off_bed_stripe_when_other_lights_on.yaml
# Purpose: Ensure mutual exclusivity between bed lights and other bedroom lights

alias: Bedroom Light Exclusivity
description: Turn off conflicting lights when another light group is turned on (bed vs non-bed)
id: bedroom-lights-exclusivity-consolidated

mode: single

trigger:
  - platform: state
    entity_id:
      - light.bedroom_bed
    from: "off"
    to: "on"
    id: bed_on

  - platform: state
    entity_id:
      - light.bedroom_jakub
      - light.bedroom_sona
      - light.bedroom_leds
      - light.bedroom_main
      - light.bedroom_reflectors
    from: "off"
    to: "on"
    id: other_on

action:
  - choose:
      - conditions:
          - condition: trigger
            id: bed_on
        sequence:
          - alias: "Turn off non-bed lights when bed lights turn on"
            action: light.turn_off
            target:
              entity_id: light.bedroom_non_bed

      - conditions:
          - condition: trigger
            id: other_on
        sequence:
          - alias: "Turn off bed stripe when other lights turn on"
            action: light.turn_off
            target:
              entity_id: light.bed_stripe
