---
alias: bedroom_switch_off_bed_stripe_when_other_lights_on
description: Turn off bed strip when any other bedroom light is turned on
id: a8f3c2d1-5e6b-4c7a-9d8e-1f2a3b4c5d6e

mode: single

trigger:
  - platform: state
    entity_id:
      - light.bedroom_jakub
      - light.bedroom_sona
      - light.bedroom_leds
      - light.bedroom_main
      - light.bedroom_reflectors
    from: "off"
    to: "on"

action:
  - alias: "Turn off the bed strip light"
    service: light.turn_off
    target:
      entity_id: light.bed_stripe
