---
alias: Jakub's Cube
description: Jakub's Cube - covers, lights, etc
id: 541daa21-c60d-4de8-ab38-c5a3d055832a

triggers:
    - domain: mqtt
      device_id: ea560cc765aa1b16e94168fed6a14041
      type: action
      subtype: shake
      trigger: device

    - trigger: state
      entity_id: sensor.jakubs_cube_side

actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.jakubs_cube_side
            state: "2"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_jakub

mode: restart

# - condition: template
#            value_template: "{{ trigger.payload == 'shake' }}"