---
alias: Jakub's Cube
description: Jakub's Cube - covers, lights, etc
id: 541daa21-c60d-4de8-ab38-c5a3d055832a
mode: restart

variables:
  non_standing_lamp_lights: >
    {{ floor_areas('ground_floor') | map('area_entities') | sum(start= []) 
    | select('match', 'light.*') | reject('search', 'light.living_room_light_standing_lamp') 
    | reject('search', 'light.toilet') | list }}

triggers:
  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: shake
    trigger: device

  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: throw
    trigger: device

  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: rotate_right
    trigger: device

  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: rotate_left
    trigger: device

  - trigger: state
    entity_id: sensor.jakubs_cube_side

actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.jakubs_cube_side
            state: "1"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == '1' }}"
                sequence:
                  - action: media_player.turn_off
                    target:
                      entity_id: media_player.living_room_tv

      - conditions:
          - condition: state
            entity_id: sensor.jakubs_cube_side
            state: "2"
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: template
                        value_template: "{{ trigger.to_state.state == '2' }}"

                      - condition: template
                        value_template: "{{ trigger.payload == 'shake' }}"

                sequence:
                  - action: light.turn_off
                    target:
                      entity_id: "{{ non_standing_lamp_lights }}"

                  - action: light.turn_on
                    target:
                      entity_id: light.living_room_light_standing_lamp

              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'throw' }}"
                sequence:
                  - action: media_player.toggle
                    target:
                      entity_id: media_player.living_room_tv

                  - service: media_player.volume_set
                    data:
                      entity_id: media_player.living_room_tv
                      volume_level: 0.22
