---
alias: Jakub's Cube
description: Jakub's Cube - covers, lights, etc
id: 541daa21-c60d-4de8-ab38-c5a3d055832a
mode: restart

triggers:
  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: shake
    trigger: device

  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: throw
    trigger: device

  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: rotate_right
    trigger: device

  - domain: mqtt
    device_id: ea560cc765aa1b16e94168fed6a14041
    type: action
    subtype: rotate_left
    trigger: device

  - trigger: state
    entity_id: sensor.jakubs_cube_side

actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.jakubs_cube_side
            state: "2"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == '2' }}"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: light.bedroom_jakub
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'shake' }}"
                sequence:
                  - action: light.toggle
                    target:
                      entity_id: light.bedroom_jakub
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'rotate_right' }}"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: light.bedroom_jakub
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'rotate_left' }}"
                sequence:
                  - action: light.turn_off
                    target:
                      entity_id: light.bedroom_jakub

      - conditions:
          - condition: state
            entity_id: sensor.jakubs_cube_side
            state: "1"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.to_state.state == '1' }}"
                sequence:
                  - action: light.turn_off
                    target:
                      area_id:
                        - bedroom
                        - main_bathroom
                  - action: media_player.turn_off
                    target:
                      area_id: bedroom

      - conditions:
          - condition: state
            entity_id: sensor.jakubs_cube_side
            state: "6"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'throw' }}"
                sequence:
                  - action: cover.set_cover_position
                    data:
                      entity_id: cover.bedroom
                      position: 20
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'shake' }}"
                sequence:
                  - action: cover.stop_cover
                    target:
                      area_id: bedroom
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'rotate_right' }}"
                sequence:
                  - action: cover.close_cover
                    target:
                      area_id: bedroom
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.payload == 'rotate_left' }}"
                sequence:
                  - action: cover.open_cover
                    target:
                      area_id: bedroom