---
alias: En suite Bathroom lights switch
description: En suite Bathroom lights switch
id: af54c161-50b6-4fd6-8839-2f2a2cd25fb7

triggers:
  - trigger: state
    entity_id:
      - sensor.bedroom_ensuite_wireless_switch

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.ensuite_bathroom_leds
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.ensuite_bathroom_main
mode: single
