---
alias: En suite Bathroom lights switch
description: En suite Bathroom lights switch
id: af54c161-50b6-4fd6-8839-2f2a2cd25fb7

triggers:
  - domain: mqtt
    device_id: 0cdbfa488fc3cf989f29e4fa01cd6520
    type: action
    subtype: 1_single
    trigger: device
  - domain: mqtt
    device_id: 0cdbfa488fc3cf989f29e4fa01cd6520
    type: action
    subtype: 2_single
    trigger: device
  - domain: mqtt
    device_id: 0cdbfa488fc3cf989f29e4fa01cd6520
    type: action
    subtype: 2_double
    trigger: device

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.ensuite_bathroom_leds
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.ensuite_bathroom_main
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_double' }}"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.ensuite_bathroom_main
              brightness_pct: 100
mode: single
