---
alias: Sona Scene Switch
description: Sona Scene Switch - covers, lights, etc
id: 8ff9934c-8fb9-4be7-98b8-fe23003785cc

triggers:
  - trigger: state
    entity_id:
      - sensor.scene_switch_jakub

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '2_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_sona
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '4_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_leds
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '2_hold' }}"
        sequence:
          - action: light.turn_off
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '4_hold' }}"
        sequence:
          - action: light.turn_off
            target:
              floor_id:
                - backyard
                - ground_floor
                - first_floor
      # Covers
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '1_single' }}"
        sequence:
          - action: cover.open_cover
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == '3_single' }}"
        sequence:
          - action: cover.close_cover
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state in ['1_double', '3_double'] }}"
        sequence:
          - action: cover.stop_cover
            target:
              area_id: bedroom

mode: single
