---
alias: Sona Scene Switch
description: Sona Scene Switch - covers, lights, etc
id: 8ff9934c-8fb9-4be7-98b8-fe23003785cc

triggers:
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 1_single
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 2_single
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 3_single
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 4_single
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 1_double
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 2_double
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 3_double
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 4_double
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 1_hold
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 2_hold
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 3_hold
    trigger: device
  - domain: mqtt
    device_id: 1a3b7e0a2d7d4b03cb7671077b0f6d77
    type: action
    subtype: 4_hold
    trigger: device

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_sona
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_single' }}"
        sequence:
          - action: light.toggle
            target:
              entity_id: light.bedroom_leds
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_hold' }}"
        sequence:
          - action: light.turn_off
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_hold' }}"
        sequence:
          - action: light.turn_off
            target:
              floor_id:
                - backyard
                - ground_floor
                - first_floor
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_double' }}"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.bedroom_sona_bulbs
              brightness_step_pct: 20

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_double' }}"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.bedroom_sona_bulbs
              brightness_step_pct: -20

      # Covers
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_single' }}"
        sequence:
          - action: cover.open_cover
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_single' }}"
        sequence:
          - action: cover.close_cover
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_double' }}"
        sequence:
          - action: cover.stop_cover
            target:
              area_id: bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_double' }}"
        sequence:
          - action: cover.set_cover_position
            data:
              entity_id: cover.bedroom
              position: 20

mode: single
