---
alias: wardrobe_lights_on_when_occupied
description: Turn on the wardrobe lights when is occupied
id: 618bc813-203f-42cc-8a55-21e89c0ca4b0

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.bedroom_wardrobe_occupancy
    from: "off"
    to: "on"
    id: "occupancy_detected"
  - platform: state
    entity_id:
      - binary_sensor.bedroom_wardrobe_occupancy
    from: "on"
    to: "off"
    for: "00:00:30"
    id: "no_occupancy_short"
  - platform: state
    entity_id:
      - binary_sensor.bedroom_wardrobe_occupancy
    from: "on"
    to: "off"
    for: "00:30:00"
    id: "no_occupancy_long"

action:
  - choose:
      # Occupancy detected - turn on light
      - conditions:
          - condition: trigger
            id: "occupancy_detected"
          - condition: state
            entity_id: light.bedroom_wardrobe
            state: "off"
        sequence:
          - alias: "Turn on the light"
            service: light.turn_on
            target:
              entity_id: light.bedroom_wardrobe
      
      # No occupancy for 30 seconds - turn off if light was turned on by automation
      - conditions:
          - condition: trigger
            id: "no_occupancy_short"
          - condition: template
            value_template: >
              {{ (now() - states.light.bedroom_wardrobe.last_changed).total_seconds() < 300 }}
        sequence:
          - alias: "Turn off the light after short delay"
            service: light.turn_off
            target:
              entity_id: light.bedroom_wardrobe
      
      # No occupancy for 30 minutes - turn off regardless (cleanup for manual control)
      - conditions:
          - condition: trigger
            id: "no_occupancy_long"
        sequence:
          - alias: "Turn off the light after long delay"
            service: light.turn_off
            target:
              entity_id: light.bedroom_wardrobe
