---
alias: wardrobe_lights_on_when_occupied
description: Turn on the wardrobe lights when is occupied
id: 618bc813-203f-42cc-8a55-21e89c0ca4b0

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.bedroom_wardrobe_occupancy
    from: "off"
    to: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.bedroom_wardrobe
            state: "off"
        sequence:
          - alias: "Turn on the light"
            service: light.turn_on
            target:
              entity_id: light.bedroom_wardrobe

          - alias: "Wait until there is no motion from device"
            wait_for_trigger:
              platform: state
              entity_id: binary_sensor.bedroom_wardrobe_occupancy
              from: "on"
              to: "off"

          - alias: "Wait the number of seconds that has been set"
            delay: 30

          - alias: "Turn off the light"
            service: light.turn_off
            target:
              entity_id: light.bedroom_wardrobe
    default:
      - alias: "Light is already on, just wait for no presence"
        wait_for_trigger:
          platform: state
          entity_id: binary_sensor.bedroom_wardrobe_occupancy
          from: "on"
          to: "off"

      - alias: "Wait 30 minutes after no presence"
        delay: "00:30:00"

      - alias: "Turn off the light"
        service: light.turn_off
        target:
          entity_id: light.bedroom_wardrobe
