---
alias: Hall presence long
description: Turn on the hall lights when they are occupied for a long period of time
id: 1c698dcf-6843-4934-9978-1b4fde5de7ea

mode: restart
max_exceeded: silent

trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.first_floor_corridor_presence
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 10
conditions: []
action:
  - choose:
      # If someone is in
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.first_floor_corridor_presence
                state: "on"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.hall_bulbs
              transition: 3
              color_temp: 454
              brightness: 255
