---
alias: Hall presence short
description: Turn on the hall lights when they are occupied for a short period of time
id: 671c0a83-a143-44c1-a406-f1bdd0073984

mode: restart
max_exceeded: silent

trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.first_floor_corridor_presence
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 5
conditions: []
action:
  - choose:
      # If someone is in
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.first_floor_corridor_presence
                state: "on"
        sequence:
          - action: light.turn_on
            data:
              entity_id: light.hall_bulbs
              transition: 2
              color_temp: 454
              brightness_pct: 30
