---
alias: Hall presence long
description: Brighten the hall lights when they are occupied for a longer period of time
id: 1c698dcf-6843-4934-9978-1b4fde5de7ea

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.first_floor_corridor_presence
    from: "off"
    to: "on"
conditions: []
action:
  - choose:
      # If someone is in after 20s
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.first_floor_corridor_presence
                state: "on"
              - condition: state
                entity_id: binary_sensor.sleeping_time
                state: "off"
        sequence:
          - delay: 20

          - if:
              - condition: state
                entity_id: light.hall_bulbs
                state: "on"
            then:
              - action: light.turn_on
                data:
                  entity_id: light.hall_bulbs
                  transition: 3
                  color_temp: 454
                  brightness: 255
