---
alias: ground_floor_turn_on_light_when_tv_switched_off
description: Turn on the lamp when TV is switched off
id: 6ef9a0a2-69d9-4379-bba7-b65c0ca0e16d

mode: single

trigger:
  - platform: state
    entity_id:
      - remote.living_room_tv
    from: "on"
    to: "off"

condition:
  - condition: state
    entity_id: binary_sensor.ground_floor_light_status
    state: "off"

  - condition: numeric_state
    entity_id: sensor.presence_sensor_fp2_livingroom_light_level
    below: 10

action:
  - service: light.turn_on
    target:
      entity_id: light.living_room_light_standing_lamp

  - alias: "Wait until there is no one in the ground floor"
    wait_for_trigger:
      platform: state
      entity_id: binary_sensor.ground_floor_occupied
      from: "on"
      to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: 10

  - service: light.turn_off
    target:
      entity_id: light.living_room_light_standing_lamp
