---
alias: ground_floor_lights_on_when_occupied
description: Turn on the lamp when someone enters the ground floor
id: 3e1eec0c-ed99-4edf-8a46-5e6852428f98

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - binary_sensor.ground_floor_occupied
    from: "off"
    to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target:
      entity_id: light.living_room_light_standing_lamp

  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: binary_sensor.ground_floor_occupied
      from: "on"
      to: "off"

  - alias: "Wait the number of seconds that has been set"
    delay: 30

  - alias: "Turn off the light"
    service: light.turn_off
    target:
      entity_id: light.living_room_light_standing_lamp
