---
alias: Toilet lights off
description: Turn on toilet lights when they are on for too long
id: ce88c77a-3be3-46da-a401-fc90fd8b8817

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: light.toilet_ambient
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 20
      seconds: 0

  - platform: state
    entity_id: light.toilet_main
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 20
      seconds: 0

action:
  - action: light.turn_off
    target:
      entity_id: "{{ trigger.entity_id }}"
